### ISSUE TITLE
CsoundServer and CsoundFileReader not recognized

### ISSUE THREAD

**Issue by afarra6** [nonameentername/godot-csound#1]
I'm definitely a composer first and (self-taught) programmer second so any help would be appreciated here. I'm trying to use WSL2 to build this GDExtension, and it does create a .lib file for the extension, however I get the following errors when I try to use the extension:

![image](https://github.com/user-attachments/assets/e3218b89-6b5f-412a-86db-ccad155c7bf1)

![image](https://github.com/user-attachments/assets/a0f9b96c-7c54-423c-a8f9-df25f9a8e1fb)

These appeared even after attempting a second build. (I can't even enable the plugin unless I comment out the trouble code) Building this also takes a very long time due to it building for a bunch of different platforms. Is there a way to only build for one? Seems like a very interesting/useful project!

Some extra info that may be useful:

Running Windows 10, using Ubuntu 22.04 through WSL2 to build

**Comment by nonameentername** [comment]
Thanks for taking the time to setup the project and try running it even though there isn't any documentation yet.
I'm currently working on getting the project to work on different platforms to be able to export to all supported Godot devices.  I'm also working from the Csound development branch and sometimes breaking changes can occur.  I might have broken the windows version when introducing changes for other devices.  I'll verify everything is working and update it if necessary.

To be able to compile for only a specific platform you can specify the name of the platform when building instead of using `all`. 

Example on how to build for each platform instead of all:
```bash
#build for ubuntu
make ubuntu

#build for windows
make mingw

#build for MacOS
make osxcross

#build for iOS
make ioscross
```

The error you are seeing is probably because Godot cannot find the gdextension dlls.
This was working previously but I moved the location of files to the addons directory to allow using it from other projects.
As a workaround you can probably add the location of the windows dlls to the PATH and then Godot will be able to load them.  You will also need to go to the project settings and under the plugin section enable the `Csound Importer`.   It wont work unless the plugin is enabled.

**Comment by afarra6** [comment]
Ah, thanks for the info! I'll see if I can't get the PATH workaround working.

**Comment by nonameentername** [comment]
I updated the build script to copy all dlls into the libcsoundgodot dir.  This will allow windows to find them when using Csound in the Godot editor.  Let me know if this does not resolve your issue.  Thanks.

**Comment by afarra6** [comment]
Seems to have done the trick! Although the Csound context is blank. I'll poke around and see if I can't figure things out on my own, but any guidance would be welcome. Thanks again!

![image](https://github.com/user-attachments/assets/13115663-d9bf-45e0-a027-3579e38e5b63)

**Comment by nonameentername** [comment]
It's expected that the Csound context at the top is empty.  I am planning on adding the ability to create instruments using graph nodes in that section but i have not gotten that far yet.  Most of the implemented functionality is available in the bottom section.

![Screenshot from 2024-08-25 23-34-31](https://github.com/user-attachments/assets/e505e7fe-c8dc-444b-a981-be946bea7979)

There are nodes on the left that are used to play Csound.  The main CsoundPlayer will play all the sounds and other channel players can be used to play specific channels.  It's also possible to have multiple Csound instances running.

There is also an audio effect that can be added to a bus that will send the sound to the specified channels as input for Csound.
This allows the ability to have in game music sent to Csound for processing.

![Screenshot from 2024-08-25 23-52-17](https://github.com/user-attachments/assets/362320ad-29fc-4097-9e71-4d1d08c5f70d)

The project has code on how to send commands to Csound.  There is a callback that will be executed when Csound is ready.
From there a reference to the instance get be retrieved from the server.

https://github.com/nonameentername/godot-csound/blob/32a73a766d359d2963d857070f4b07957b701350/main.gd#L8-L14

The Csound instance can then be used to play notes, etc.

https://github.com/nonameentername/godot-csound/blob/32a73a766d359d2963d857070f4b07957b701350/main.gd#L35-L43
