### ISSUE TITLE
A minimal usage example?

### ISSUE THREAD

**Issue by flaviotordini** [nonameentername/godot-csound#2]
Very interesting project, thank you! I already built it. Could you provide a usage example to get me started quickly?

**Comment by nonameentername** [comment]
Hello, and thank you for taking the time to explore godot-csound!

Please note that this project relies on the development branch of Csound, so breaking changes may occur in the future as it's still a work in progress.

To help you get started, I've created a simple example Godot project that uses godot-csound, which you can find [here](https://github.com/nonameentername/godot-csound-example).

For a more advanced example, check out [this project](https://github.com/nonameentername/godot-synths).

**Comment by flaviotordini** [comment]
Thanks, the simple example crashes Godot. I reported the log here: https://github.com/nonameentername/godot-csound-example/issues/1

Anyway I'm reading the code and trying to implement it in my project. I get the same FATAL error:

E 0:00:02:0224   operator[]: FATAL: Index p_index = 1024 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 1024).

Any idea?

**Comment by nonameentername** [comment]
I believe I’ve identified the reason why the project is failing on macOS. I’ve made updates to godot-csound that should resolve the issue, but I won’t be able to verify the fix until I have access to my macOS desktop.

The issue seems to stem from a recent change in Csound, where plugins are now built as separate shared libraries by default. This causes certain opcodes to be unavailable when running Csound. The solution is to build Csound with the plugins included directly, rather than as separate shared libraries.

Additionally, I’ve added an option to display Csound logs, the option can be found under the advanced audio settings.
