### ISSUE TITLE
AudioStreamPlayer scene setup

### ISSUE THREAD

**Issue by flaviotordini** [nonameentername/godot-csound#3]
I've been trying to make godot-sound csound work in my project as it does in the example. I rebuilt with the latest changes and I tried to mimic the AudioStreamPlayer nodes as in the example.

I cannot get the csound_ready signal to be emitted. Instead I get:

```
W 0:00:02:0054   push_warning: Csound is not active. AudioStreamCsound should be started before AudioStreamCsoundChannel.
  <C++ Source>   core/variant/variant_utility.cpp:1112 @ push_warning()
```

When i fiddle with the "Csound" tab in the bottom panel, a "default_csound_layout.tres" file is created. When this file is present `csound_ready` is emitted but I start also getting the following fatal error:

```
E 0:00:02:0310   operator[]: FATAL: Index p_index = 1024 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 1024).
  <C++ Source>   godot-cpp/include/godot_cpp/templates/vector.hpp:54 @ operator[]()
```

**Comment by nonameentername** [comment]
Hello @flaviotordini.  Would you be able to add your project to GitHub or provide a tarball/zip file to help reproduce the error?

The `default_csound_layout.tres` file is essential as it keeps track of the running Csound instances. Additionally, ensure that you have a valid Csound.csd file specified under the Csound tab. This file is read when Csound starts, and the error you're encountering might be due to it not being set.

Let me know if you have any additional questions.

**Comment by flaviotordini** [comment]
Yes, in the meantime I found out that by loading your test.csd in the Csound "mixer" ui, I can make it work. Actually I don't want to load a fixed csd on startup. I want to load it programmatically.

**Comment by nonameentername** [comment]
@flaviotordini I updated the project to display an error message when the Csound CSD script is not found.  I also do not start the Csound thread if the CSD is missing or there are errors in the CSD file.
